---
- name: Create pods using deployment
# kubernetes master has the deploy and service yml
  hosts: kubernetes
  become: true
  user: root
  vars:
    commit: '{{ imageTag }}'
  environment:
    IMAGE_TAG: '{{ commit }}'

# to replace ENV variable use envsubst. install it on you master server
# to install it run sudo apt-get update && sudo apt-get -y install gettext-base
  tasks:
  - name: replase env variables
    shell: envsubst < valaxy-deploy.template > valaxy-deploy.yml

  - name: create a deployment
    command: kubectl apply -f valaxy-deploy.yml

  - name: update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment.v1.apps/valaxy-deployment
